export const styles = {
  container: "flex-1 bg-secondary-50 dark:bg-secondary-950",
  content: "p-6",
  welcomeSection: "mb-6",
  welcomeTitle: "text-2xl font-bold text-secondary-900 dark:text-white",
  welcomeSubtitle: "mt-1 text-secondary-500",
  premiumBanner: "mb-6 bg-primary-500",
  premiumBannerContent: "flex-row items-center justify-between",
  premiumBannerTextContainer: "flex-1",
  premiumBannerTitle: "text-lg font-semibold text-white",
  premiumBannerSubtitle: "mt-1 text-sm text-primary-100",
  sectionTitle: "mb-3 text-lg font-semibold text-secondary-900 dark:text-white",
  actionCards: "gap-3",
  actionCardContent: "flex-row items-center",
  actionIconContainer: "mr-4 h-12 w-12 items-center justify-center rounded-full",
  actionIconContainerPrimary: "bg-primary-100",
  actionIconContainerGreen: "bg-green-100",
  actionIconContainerPurple: "bg-purple-100",
  actionIcon: "text-2xl",
  actionTextContainer: "flex-1",
  actionTitle: "font-semibold text-secondary-900 dark:text-white",
  actionSubtitle: "text-sm text-secondary-500",
} as const;
