export const styles = {
  keyboardAvoidingView: "flex-1 bg-white dark:bg-secondary-950",
  scrollContent: { flexGrow: 1 },
  content: "flex-1 justify-center px-6 py-12",
  header: "mb-10",
  title: "text-3xl font-bold text-secondary-900 dark:text-white",
  subtitle: "mt-2 text-base text-secondary-500",
  form: "gap-4",
  forgotPasswordLink: "self-end text-sm font-medium text-primary-600",
  submitButton: "mt-4",
  divider: "my-8 flex-row items-center",
  dividerLine: "flex-1 h-px bg-secondary-200 dark:bg-secondary-700",
  dividerText: "mx-4 text-sm text-secondary-500",
  socialButtons: "gap-3",
  footer: "mt-8 flex-row justify-center",
  footerText: "text-secondary-600 dark:text-secondary-400",
  footerLink: "font-semibold text-primary-600",
} as const;
